config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users, :controllers => {
  	:registrations => 'users/registrations'} 

  get '/users/menu' => 'users#menu', as: 'menu'
  resources :users, :only => [:index, :show]

  resources :posts do
    resources :orders, :only => [:new, :create, :edit, :update, :destroy]
  end

  root 'posts#index'
  get '/orders' => 'orders#index', as: 'orders'
  get '/orders/:id' => 'orders#show', as: 'order'
  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    validates :username, presence: true
    VALID_USEREMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      validates :email, presence: true, format: { with: VALID_USEREMAIL_REGEX }
    validates :encrypted_password, presence: true
  has_many :posts, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    before_action :require_no_authentication, :only => [:cancel]
  #  before_action :authenticate_scope!, :only => [:new, :create ,:edit, :update, :destroy]
    
    add_breadcrumb "アカウント管理"

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    add_breadcrumb '管理者メニュー', :menu_path
    add_breadcrumb "アカウント登録", :new_user_registration_path
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    add_breadcrumb "アカウントの編集", :edit_user_registration_path
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  def after_sign_up_path_for(resource)
    user_path(resource)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :correct_user, only: [:index, :menu]

  add_breadcrumb "アカウント管理"

  def index
  	@users = User.all
    add_breadcrumb '管理者メニュー', :menu_path
    add_breadcrumb "ユーザー一覧", :users_path
  end

  def show
  	@user = User.find(params[:id])
    @orders = @user.orders.all.includes(:post)
  	@posts = @user.posts.all.includes(:post_images)
    @image = PostImage.first

    if user_signed_in? && current_user.id == @user.id
      add_breadcrumb "マイページ", :user_path
    else
      add_breadcrumb @user.username, :user_path
    end
  end

  def menu
    add_breadcrumb "管理者メニュー", :menu_path    
  end

  private
    def correct_user
      if current_user.admin?
      else
        redirect_to user_path
      end
    end
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="body">
  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>

  <h1 class="h1-text">ユーザー一覧</h1>

  <div class="section">
	<table class="user_table">
  	  <thead>
  		<tr>
	  	  <th width="20%">ユーザー<br>ネーム</th>
	  	  <th width="30%">メール<br>アドレス</th>
	  	  <th width="30%">アカウント<br>作成日</th>
	  	  <th width="20%">ステータス</th>
		</tr>
  	  </thead>
  	  <tbody>
		<% @users.each do |user| %>
	  	  <tr>
	    	<td height="30px" align="center"><%= link_to user.username, "/users/#{user.id}" %></td>
	    	<td height="30px" align="center"><%= user.email %></td>
	    	<td height="30px" align="center"><%= user.created_at.strftime("%Y/%m/%d") %></td>
	    	<% if user.admin? %>
	    	  <td height="30px" align="center">管理者</td>
	    	<% else %>
	    	  <td height="30px" align="center">ユーザー</td>
	    	<% end %>
	  	  </tr>
		<% end %>
  	  </tbody>
	</table>
  </div>
</div>

app/views/users/menu.html.erb
<div class="body">
	<div class="breadcrumbs" >
    	<%= render_breadcrumbs separator: ' > ' %>
	</div>
	<h1 class="h1-text">管理者用メニュー一覧</h1>

	<div class="section">
		<div class="adminmenu"><%= link_to '出品する', new_post_path %></div>
		<div class="adminmenu"><%= link_to '全購入履歴', orders_path %></div>
		<div class="adminmenu"><%= link_to 'ユーザー一覧', users_path %></div>
		<div class="adminmenu"><%= link_to '新規ユーザー登録', new_user_registration_path %></div>
		<div class="adminmenu"><%= link_to 'カテゴリ一覧', categories_path %></div>
		<div class="adminmenu"><%= link_to 'カテゴリ作成', new_category_path %></div>
	</div>
</div>

app/views/users/show.html.erb
<div class="body">
  <p id="notice"><%= notice %></p>
  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>

  <% if user_signed_in? && current_user.id == @user.id  %>
  	<h1 class="h1-text">マイページ</h1>
  <% else %>
		<h1 class="h1-text"><%= @user.username %>さんのページ</h1>
  <% end %>

  <div class="index_section">
    <% if user_signed_in? %>
      <% if current_user.admin? || current_user.id == @user.id %>
	      <div class="section-container">
		      <table class="user_table">
  	    	  <thead>
  			      <tr>
	  	  	      <th width="30%">ユーザーネーム</th>
	  	  	      <th width="40%">メールアドレス</th>
	  	  	      <th width="30%">アカウント作成日</th>
  			      </tr>
    	  	  </thead>
  	    	  <tbody>
			        <tr>
	  	    	    <td align="center"><%= @user.username %></td>
	  	  	      <td align="center"><%= @user.email %></td>
	  	  	      <td align="center"><%= @user.created_at.strftime("%Y/%m/%d") %></td>
			        </tr>
  	  	    </tbody>
		      </table>
          <% if current_user.id == @user.id %>
            <div class="navigate clearfix">
              <div class="right">
                <%= link_to "ユーザー情報編集", edit_user_registration_path %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="line"></div>
      <% end %>

      <div class="clearfix">
        <% if current_user.admin? %>
          <div class="navigate clearfix">
            <h4 class="right"><%= link_to '全購入履歴一覧を見る', orders_path %></h4>
          </div>
        <% end %>
        <% if current_user.id == @user.id %>
          <h3 class="h3-text">あなたの購入履歴</h3>
        <% else %>
          <% if current_user.admin? %>
            <h3 class="h3-text"><%= @user.username %>さんの購入履歴</h3>
          <% end %>
        <% end %>
      </div>

      <% if current_user.admin? || current_user.id == @user.id %>
        <div class="section-container">
          <% if @user.orders.count == 0 %>
            <div class="text-center">注文履歴はありません</div>
          <% else %>
            <table class="table" rules="rows">
              <thead>
                <th width="20%">注文ID</th>
                <th width="30%">商品名</th>
                <th width="20%">価格</th>
                <th width="30%">購入日</th>
              </thead>
  
              <% @orders.reverse_each do |order| %>
                <tbody>
                  <td height="30" align="center"><%= link_to order.id, order_path(order.id) %></td>
                  <td align="center"><%= link_to order.post.title, post_path(order.post_id) %></td>
                  <td align="center"><%= number_to_currency(order.post.price, :precision => 0, :unit => '¥') %></td>
                  <td align="center"><%= order.created_at.strftime('%Y/%m/%d') %></td>
                </tbody>
              <% end %>
            </table>
          <% end %>
        </div>
        <div class="line"></div>
      <% end %>
    <% end %>
  
    <div class="section-container">
      <% if user_signed_in? && current_user.admin? && current_user.id == @user.id %>
	       <h3 class="h3-text">あなたが出品した作品<small>(<%= @posts.count %>件)</small></h3>
      <% else %>
        <% if @user.admin? %>
	        <h3 class="h3-text"><%= @user.username %>さんが出品した商品<small>(<%= @posts.count %>件)</small></h3>
        <% end %>
      <% end %>

      <div class="index_section_posts clearfix">
        <% @posts.reverse_each do |post| %>
          <div class="left index_post_box">
            <% if post.post_images.present? %>
              <div class="post_image">
                <%= attachment_image_tag @image, :image, :fill, 150, 150 %>
              </div>
            <% else %>
              <div class="post_image">
                <%= image_tag 'l_e_others_501.png', size: '150x150' %>
              </div>
            <% end %>
            <div class="clearfix post_text">
              <div class="left post_title">
                <%= link_to post.title, post_path(post) %>
              </div>
              <div class="right post_price" >
                <%= number_to_currency(post.price, :precision => 0, :unit => '¥') %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>