config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users, :controllers => {
  	:registrations => 'users/registrations'} 

  get '/users/menu' => 'users#menu', as: 'menu'
  resources :users, :only => [:index, :show]

  resources :posts do
    resources :orders, :only => [:new, :create, :edit, :update, :destroy]
  end

  root 'posts#index'
  get '/orders' => 'orders#index', as: 'orders'
  get '/orders/:id' => 'orders#show', as: 'order'
  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :post
	belongs_to :user

	paginates_per 20

	validates :ordername, presence: true

	VALID_PHONE_REGEX = /\A\d{10}$|^\d{11}\z/
	validates :orderphone, presence: true,
						   format: { with: VALID_PHONE_REGEX }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :orderemail, presence: true,
						   format: { with: VALID_EMAIL_REGEX }
						   
	validates :orderaddress, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:index]

  add_breadcrumb "注文"

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.order(created_at: :desc).page(params[:page]).includes(:post, :user)
    add_breadcrumb '管理者メニュー', :menu_path
    add_breadcrumb "購入履歴一覧"
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    # @post = Post.find(params[:post_id])
    add_breadcrumb "注文者情報"
  end

  # GET /orders/new
  def new
    @order = Order.new
    @post = Post.find(params[:post_id])
    add_breadcrumb "新規注文"
    if user_signed_in?
    else
      redirect_to new_user_session_path
    end
  end

  # GET /orders/1/edit
  def edit
    add_breadcrumb "購入者情報", :order_path
    add_breadcrumb "編集"
  end

  # POST /orders
  # POST /orders.json
  def create
    @post = Post.find(params[:post_id])
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.post_id = @post.id

    respond_to do |format|
      if @order.save
        OrderMailer.send_when_order(@order).deliver
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:post_id, :user_id, :ordername, :orderphone, :orderemail, :orderaddress)
    end

    def correct_user
      # order = Order.find(params[:id])
      if current_user.admin?
      else
        redirect_to root_path
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, url: post_orders_path, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %>件のエラーが出ています。</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'お名前' %>
    <%= form.text_field :ordername, :size=>"65x1", id: :order_ordername %>
  </div>

  <div class="field">
    <%= form.label '電話番号' %>
    <%= form.telephone_field :orderphone, :size=>"65x1", id: :order_orderphone %>
  </div>

  <div class="field">
    <%= form.label 'メールアドレス' %>
    <%= form.text_field :orderemail, :size=>"65x1", id: :order_orderemail %>
  </div>

  <div class="field">
    <%= form.label 'ご住所' %>
    <%= form.text_field :orderaddress, :size=>"65x1", id: :order_orderaddress %>
  </div>

  <div class="actions button">
    <%= form.submit '注文する' %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="body">

  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>

  <h1 class="h1-text">購入者情報の編集</h1>

  <div class="section">
  	<div class="form"><%= render 'form', order: @order %></div>
  	<div class="navigate clearfix">
  	  <div class="right">
  		<%= link_to '戻る', @order %>
  	  </div>
  	</div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="body">

  <p id="notice"><%= notice %></p>

  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>

  <h1 class="h1-text">購入履歴一覧</h1>

  <div class="section">
    <div class="clearfix">
        <div class="right index_section_page"><%= paginate(@orders) %><br><br></div>
    </div>
    <table>
      <thead>
        <tr>
          <th width="10%">注文ID</th>
          <th width="20%">商品名</th>
          <th width="25%">購入した<br>ユーザー</th>
          <th width="20%">購入金額</th>
          <th width="25%">購入日</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td align="center"><%= link_to order.id, order_path(order.id) %></td>
            <td align="center"><%= link_to order.post.title, post_path(order.post_id) %></td>
            <td align="center"><%= link_to order.user.username, user_path(order.user_id) %></td>
            <td align="center"><%= number_to_currency(order.post.price, :precision => 0, :unit => '¥') %></td>
            <td align="center"><%= order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/new.html.erb
<div class="body">

  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>

  <h1 class="h1-text">注文者情報</h1>

  <div class="section">
	<div class="form">
		<div>
			購入する商品:<%= link_to @post.title, post_path(@post.id) %>
			<%= number_to_currency(@post.price, :precision => 0, :unit => '¥') %>
		</div><br>
		<div><%= render 'form', order: @order %></div>
	</div>

	<div class="clearfix">
	  <div class="navigate right">
	    <%= link_to '戻る', post_path(@post.id) %>
	  </div>
	</div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="body">

  <p id="notice"><%= notice %></p>

  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>

  <h1 class="h1-text">購入者情報</h1>

  <div class="index_section">
    <div class="order-box clearfix">
      <div class="post-order-image clearfix">
        <% if @order.post.post_images.present? %>
          <% @order.post.post_images.each do |image| %>
            <div class="left image">
              <%= attachment_image_tag image, :image, :fill, 150, 150 %>
            </div>
          <% end %>
        <% else %>
          <div><%= image_tag 'l_e_others_501.png', size: '150x150' %></div>
        <% end %>
      </div>
      <div class="order-info">
        <p>
          <strong>商品名:</strong>
          <%= link_to @order.post.title, post_path %>
        </p>
        
        <p>
          <strong>注文者:</strong>
          <%= link_to @order.user.username, user_path(@order.user) %>
        </p>
        
        <p>
          <strong>購入者氏名:</strong>
          <%= @order.ordername %>
        </p>
        
        <p>
          <strong>連絡先:</strong>
          <%= @order.orderphone %>
        </p>
        
        <p>
          <strong>メールアドレス:</strong>
          <%= @order.orderemail %>
        </p>
        
        <p>
          <strong>送付先住所:</strong>
          <%= @order.orderaddress %>
        </p>
        <div class="clearfix">
          <div class="navigate right">
            <br>
            <% if current_user.admin? %>
              <%= link_to '編集', edit_post_order_path(@order) %> | 
            <% end %>
            <%= link_to '戻る', post_path(@order.post_id) %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>