config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users, :controllers => {
  	:registrations => 'users/registrations'} 

  get '/users/menu' => 'users#menu', as: 'menu'
  resources :users, :only => [:index, :show]

  resources :posts do
    resources :orders, :only => [:new, :create, :edit, :update, :destroy]
  end

  root 'posts#index'
  get '/orders' => 'orders#index', as: 'orders'
  get '/orders/:id' => 'orders#show', as: 'order'
  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	belongs_to :category

	has_many :post_images, dependent: :destroy
	has_many :orders, dependent: :destroy
	
	accepts_attachments_for :post_images, attachment: :image
	paginates_per 30

	validates :title, presence: true
	validates :price, presence: true
	validates :body, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  add_breadcrumb "商品"

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page]).includes(:post_images)
    @image = PostImage.first
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    add_breadcrumb @post.title, :post_path
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.post_images.build
    add_breadcrumb '管理者メニュー', :menu_path
    add_breadcrumb '出品', :new_post_path
  end

  # GET /posts/1/edit
  def edit
    add_breadcrumb @post.title, :post_path
    add_breadcrumb '商品情報の編集', :edit_post_path
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :price, :body, :category_id, post_images_images: [])
    end
    def correct_user
      post = Post.find(params[:id])
      if current_user.admin?
      else
        if current_user.id != post.user.id
          redirect_to new_user_session_path
        end
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %>件のエラーが出ています。</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "商品名" %>
    <%= form.text_field :title, :size=>"65x1", id: :post_title %>
  </div>

  <div class="field">
    <%= form.label "イメージ" %>
    <%= form.attachment_field :post_images_images, multiple: true %>
  </div>

  <div class="field">
    <%= form.label "イメージ2" %>
    <%= form.attachment_field :post_images_images, multiple: true %>
  </div>

  <div class="field">
    <%= form.label "イメージ3" %>
    <%= form.attachment_field :post_images_images, multiple: true %>
  </div>

  <div class="field">
    <%= form.label "価格" %>
    <%= form.number_field :price, :size=>"65x1", id: :post_price %>
  </div>

  <div class="area">
    <%= form.label "紹介" %>
    <%= form.text_area :body, :size=>"65x10", id: :post_body %>
  </div>

  <div class="field">
    <%= form.label "カテゴリ" %>
    <%= form.collection_select :category_id, Category.all, :id, :categoryname %>
  </div>

  <div class="actions button">
    <%= form.submit "出品する" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="body">
  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>

  <h1 class="h1-text">商品詳細の編集</h1>

  <div class="section">
	<div class="form"><%= render 'form', post: @post %></div>

 	<div class="navigate clearfix">
	  <div class="right">
		<%= link_to '詳細画面に戻る', @post %> |
		<%= link_to '一覧に戻る', posts_path %>
	  </div>
	</div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="body">
  <p id="notice"><%= notice %></p>

  <h1 class="h1-text">商品一覧</h1>

  <div class="index_section">
    <div class="index_section_page clearfix">
      <div class="right clearfix">
        <div class="left"><%= paginate(@posts) %></div>
        <div class="left"> | <%= page_entries_info(@posts) %></div>
      </div>
    </div>
    <div class="index_section_posts clearfix">
      <% @posts.reverse_each do |post| %>
        <div class="left index_post_box">
          <% if post.post_images.present? %>
            <div class="post_image">
              <%= attachment_image_tag @image, :image, :fill, 150, 150 %>
            </div>
          <% else %>
            <div class="post_image">
              <%= image_tag 'l_e_others_501.png', size: '150x150' %>
            </div>
          <% end %>
          <div class="clearfix post_text">
            <div class="left post_title">
              <%= link_to post.title, post_path(post) %>
            </div>
            <div class="right post_price" >
              <%= number_to_currency(post.price, :precision => 0, :unit => '¥') %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <div class="index_section_page"><%= paginate(@posts) %></div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="body">
  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>

  <h1 class="h1-text">出品する</h1>

  <div class="section">
	  <div class="form"><%= render 'form', post: @post %></div>

	  <div class="clearfix">
  	  <div class="navigate right">
		    <%= link_to '戻る', posts_path %>
	    </div>
	  </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="body">
  <p id="notice"><%= notice %></p>

  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>

  <h1 class="h1-text">商品詳細</h1>

  <div class="section">
    <div class="post-box">
      <div class="image-box clearfix">
        <% if @post.post_images.present? %>
          <% @post.post_images.each do |image| %>
            <div class="image left">
              <%= attachment_image_tag image, :image, :fill, 150, 150 %>
            </div>
          <% end %>
        <% else %>
          <div class="image left">
            <%= image_tag 'l_e_others_501.png', size: '150x150' %>
          </div>
        <% end %>
      </div>
      <div class="text-box">
        <div class="clearfix">
          <div class="left text">
            <p><%= @post.title %></p>
            <p><%= number_to_currency(@post.price, :precision => 0, :unit => '¥') %></p>
          </div>
          <div class="left text">
            <p>出品者:<%= link_to @post.user.username, user_path(@post.user) %></p>
            <p>カテゴリ:<%= link_to @post.category.categoryname, category_path(@post.category) %></p>
          </div>
        </div>
        <div class="content">
          <%= simple_format(@post.body) %>
        </div>
      </div>
    </div>

    <div class="button">
      <%= button_to 'この商品を注文する', new_post_order_path(@post), method: :get %>
    </div>

    <div class="clearfix">
      <div class="navigate right">
        <% if user_signed_in? %>
	        <% if current_user.admin? || current_user.id == @post.user_id %>
	 	        <%= link_to '編集', edit_post_path(@post) %> | 
		        <%= link_to '削除', @post, method: :delete, data: { confirm: '本当に削除しますか?' } %> | 
	        <% end %>
        <% end %>
        <%= link_to '戻る', posts_path %>
      </div>
    </div>
  </div>
</div>