config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users, :controllers => {
  	:registrations => 'users/registrations'} 

  get '/users/menu' => 'users#menu', as: 'menu'
  resources :users, :only => [:index, :show]

  resources :posts do
    resources :orders, :only => [:new, :create, :edit, :update, :destroy]
  end

  root 'posts#index'
  get '/orders' => 'orders#index', as: 'orders'
  get '/orders/:id' => 'orders#show', as: 'order'
  


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
	paginates_per 20
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:index, :new, :create, :edit, :update, :destroy]

  

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.page(params[:page])
    add_breadcrumb "アカウント管理"
    add_breadcrumb '管理者メニュー', :menu_path
    add_breadcrumb 'カテゴリ一覧'
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @posts = @category.posts.page(params[:page]).includes(:post_images)
    @image = PostImage.first
    add_breadcrumb "商品"
    add_breadcrumb @category.categoryname, :category_path
  end

  # GET /categories/new
  def new
    @category = Category.new
    add_breadcrumb "アカウント管理"
    add_breadcrumb '管理者メニュー', :menu_path
    add_breadcrumb 'カテゴリ作成'
  end

  # GET /categories/1/edit
  def edit
    add_breadcrumb "アカウント管理"
    add_breadcrumb '管理者メニュー', :menu_path
    add_breadcrumb 'カテゴリ編集'
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :index, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:categoryname)
    end

    def correct_user
      #category = Category.find(params[:id])
      if current_user.admin?
      else
        redirect_to root_path
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :カテゴリ %>
    <%= form.text_field :categoryname, :size=>"70x1", id: :category_categoryname %>
  </div>

  <div class="actions button">
    <%= form.submit '作成する' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="body">

  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>
  
  <h1 class="h1-text">カテゴリ編集</h1>
  
  <div class="section">
  	<div class="form">
	  <%= render 'form', category: @category %>
	</div>
	<div class="clearfix">
	  <div class="navigate right">
		<%= link_to '戻る', categories_path %>
	  </div>
	</div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="body">

  <p id="notice"><%= notice %></p>

  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>

  <h1 class="h1-text">カテゴリ一覧</h1>

  <div class="section">
    <div class="index_section_page clearfix">
      <div class="right clearfix">
        <div class="left"><%= paginate(@categories) %></div>
        <div class="left"> | <%= page_entries_info(@categories) %></div>
      </div>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= link_to category.categoryname, category_path(category) %></td>
            <td><%= link_to '編集', edit_category_path(category) %></td>
            <td><%= link_to '削除', category, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <div class="clearfix">
      <div class="navigate right">
        <%= link_to 'カテゴリ作成', new_category_path %>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="body">

  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>

  <h1 class="h1-text">カテゴリ作成</h1>

  <div class="section">
  	<div class="form">
	  <%= render 'form', category: @category %>
	</div>
    <div class="clearfix">
      <div class="navigate right">
	    <%= link_to '戻る', categories_path %>
	  </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="body">
  <p id="notice"><%= notice %></p>

  <div class="breadcrumbs" >
    <%= render_breadcrumbs separator: ' > ' %>
  </div>

  <h1 class="h1-text"><%= @category.categoryname %></h1>

  <div class="index_section">
    <div class="index_section_page clearfix">
      <div class="right clearfix">
        <div class="left"><%= paginate(@posts) %></div>
        <div class="left"> | <%= page_entries_info(@posts) %></div>
      </div>
    </div>
    <div class="index_section_posts clearfix">
      <% @posts.reverse_each do |post| %>
        <div class="left index_post_box">
          <% if post.post_images.present? %>
            <div class="post_image">
              <%= attachment_image_tag @image, :image, :fill, 150, 150 %>
            </div>
          <% else %>
            <div class="post_image">
              <%= image_tag 'l_e_others_501.png', size: '150x150' %>
            </div>
          <% end %>
          <div class="clearfix post_text">
            <div class="left post_title">
              <%= link_to post.title, post_path(post) %>
            </div>
            <div class="right post_price" >
              <%= number_to_currency(post.price, :precision => 0, :unit => '¥') %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <div class="index_section_page"><%= paginate(@posts) %></div>
  </div>
	<div class="clearfix">
	  <div class="navigate right">
		<%= link_to '戻る', categories_path %>
	  </div>
	</div>
  </div>
 </div>